#!/usr/bin/env bash
# This is a script to loop "To infinity and beyond" forever and prints I am invincible!!! when receiving sigterm signal
trap "echo I am invincible!!!" SIGTERM SIGINT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
