#!/usr/bin/env bash
# This script will print Holberton School 10 times but hi on the 9th time

i=1
while [ $i -lt 11 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    ((i ++ ))
done
