#!/usr/bin/env bash
# This script will print Holberton School 10 times but hi on the 9th time

i=1
while [ $i -lt 21 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 9 ]
    then
        echo "good luck"
    elif [ $i -eq 17 ]
    then
	echo "bad luck from Italy"
    else
        echo "Holberon School"
    fi
    ((i++))
done