#!/usr/bin/env bash
# This script will print Holberton School 10 times but hi on the 9th time

i=1
while [ $i -lt 21 ]
do
    case $i in

        4)
	    echo $i
	    echo "bad luck from China"
	    ;;

	9)
	    echo $i
	    echo "bad luck from Japan"
	    ;;

	17)
	    echo $i
	    echo "bad luck from Italy"
	    ;;

	*)
	    echo $i
	    ;;
    esac

    (( i++ ))
done
