#!/usr/bin/env bash                                                   
# This is a scrip to display time for a project                                                         
h=0
while (( h < 13 ))
do
  echo Hour: $h
  ((h++))
  m=1
  while (( m < 60 ))
  do
  echo $m
  ((m++))
  done
done
